// react/todo-list/src/Components/TodoList.js
import React from "react";

export default class TodoList extends React.Component {
  constructor(props) {
    super(props);

    this.addNewTask = this.addNewTask.bind(this);

    this.props.tasksService.getTasks().subscribe((results) => {
      this.state = {
        tasks: results,
      };
    });
  }

  addNewTask() {
    const newTask = {
      id: this.state.tasks.length + 1,
      label: "New task",
      complete: false,
    };

    // this.tasksService.addTask(newTask);

    this.state.tasks.push(newTask);
    this.setState({ tasks: this.state.tasks });
  }

  handleChange(e, id) {
    const task = this.state.tasks.find((task) => {
      return task.id === id;
    });
    task.complete = e.target.checked;
    this.setState({ tasks: this.state.tasks });
  }

  render() {
    const tasksList = this.state.tasks.map((task) => (
      <li key={task.id}>
        {task.label}
        <span>
          <input
            type="checkbox"
            value=""
            onChange={(e) => this.handleChange(e, task.id)}
          />
        </span>
      </li>
    ));

    return (
      <div>
        <button onClick={this.addNewTask}>New task</button>

        <ul>{tasksList}</ul>

        <pre>{JSON.stringify(this.state.tasks, null, 2)}</pre>
      </div>
    );
  }
}

// angular/todo-list/src/app/components/todo-list.component.ts
import { Component, OnInit } from '@angular/core';
import { TasksService } from '../services/tasks.service';
import { Task } from '../models/task';

@Component({
    selector: 'todo-list',
    templateUrl: 'todo-list.component.html',
    styleUrls: ['todo-list.component.css']
})
export class TodoListComponent implements OnInit {

    tasks: Task[] = [];

    constructor(public tasksService: TasksService) {
    }

    ngOnInit() {
        this.tasksService.$data.subscribe(results => this.tasks = results);
    }

    addNewTask() {
        const newTask = {
            id: this.tasks.length,
            label: 'New task',
            complete: false
        };

        this.tasksService.addTask(newTask);
    }
}
<button (click)="addNewTask()">New task</button>

<ul>
    <li *ngFor="let task of tasks">
        {{task.label}}
        <span>
            <input type="checkbox" value="checked"
                [(ngModel)]="task.complete" />
        </span>
    </li>
</ul>

<pre>{{tasks | json}}</pre>
